drop table if exists cards, cardholders;
drop sequence if exists seq_gen_sequence;
CREATE SEQUENCE IF NOT EXISTS SEQ_GEN_SEQUENCE START WITH 500 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CARDS(
    ID INT PRIMARY KEY,
    ACTIVATED_DATE DATE,
    ACTUAL_BALANCE NUMERIC(20,2),
    AVAILABLE_BALANCE NUMERIC(20,2),
    CARD_NUMBER CHAR(16) UNIQUE,
    CREATED_DATE DATE,
    EXPIRY_DATE DATE,
    PRIMARY_SECONDARY_INDICATOR BOOLEAN,
    STATUS VARCHAR(10)
);
CREATE TABLE IF NOT EXISTS CARDHOLDERS(
 IDENTITY_NUMBER CHAR(13) PRIMARY KEY,
 DATE_OF_BIRTH DATE NOT NULL,
 FIRST_NAME VARCHAR(25) NOT NULL,
 SURNAME VARCHAR(25) NOT NULL,
 TITLE VARCHAR(5)
);
